language: python

python:
  - "3.6"

before_install:
  - cp catalog/config.default.py catalog/config.py

install: pip3 install -e .

# services:
  # - postgresql

# env:
#   global:
#   - REPO="clinical-charts"
#   - FILES="output/"
#   - GITHUB_REPO="github.com/linewalks/${REPO}.git"

script:
  - flake8 catalog tests
  # - pytest -m base -s tests/
